import React from "react";
import Head from "next/head";
import Header from "./header";
import Footer from "./footer";


const Layout = ({ children, pagina, guitarra,checkout }) => {
  return (
    <div>
      <Head>
        <title>GuitarLA - {pagina}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header
      guitarra={guitarra}
       />

      {children}

    {checkout ? null :   <Footer /> }
    </div>
  );
};

Layout.defaultProps = {
  guitarra: null,
};

export default Layout;
